[build]
    functions = "functions"
[[headers]]
  # Configuração para permitir qualquer origem
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
      Content-Type = "application/pdf"
      Content-Disposition = "attachment; filename=seu_arquivo.pdf"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200